//! Utilities for converting between [`usize`]s and fixed-size integrals in wgpu, mostly
//! [`usize_from_u32`].
//!
//! wgpu crates only support 32-bit targets. This module both enforces this at compile time, and
//! offers conveniences for converting between [`u32`] and [`usize`] that [`core`] cannot provide,
//! because Rust's minimum assumed word size is 16 bits.

use core::{
    error,
    fmt::{self, Formatter},
};

/// An error generated by [`u32_from_external_usize`].
#[derive(Debug)]
pub struct U32FromExternalUsizeError {
    value: usize,
}

impl error::Error for U32FromExternalUsizeError {}

impl fmt::Display for U32FromExternalUsizeError {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let Self { value } = self;
        write!(
            f,
            "failed to convert externally provided `usize` to `u32` with value of {value}"
        )
    }
}

/// Convert a [`usize`] to a [`u32`] from wgpu internals that should panic if conversion fails.
#[track_caller]
pub fn u32_from_internal_usize(n: usize) -> u32 {
    n.try_into().unwrap_or_else(|_e| {
        unreachable!(
            concat!(
                "internal `usize` value was expected by wgpu internals ",
                "to fit in the `u32` value range, value was {}"
            ),
            n
        )
    })
}

/// Convert a [`usize`] to a [`u32`] from a boundary that needs to be checked.
///
/// This is intended to be used for wgpu internals instead of [`TryFrom`] both to document intent
/// and to provide somewhat better diagnostics by default.
pub fn u32_from_external_usize(n: usize) -> Result<u32, U32FromExternalUsizeError> {
    n.try_into()
        .map_err(|_e| U32FromExternalUsizeError { value: n })
}

/// Convert a [`u32`] to a [`usize`].
pub const fn usize_from_u32(n: u32) -> usize {
    const _: () = assert!(
        size_of::<usize>() >= size_of::<u32>(),
        "word sizes < 32 bits are not supported in wgpu crates"
    );
    n as usize
}
